service: video-queue
frameworkVersion: "4.2.5"

provider:
    name: aws
    runtime: nodejs20.x
    region: ap-south-1 # Specify your region
    deploymentBucket:
        name: bucket-4-serverless-deployment # Replace with your bucket name

functions:
    makeFormats:
        name: make-formats
        handler: makeFormats.handler
        events:
            - sqs:
                  arn: arn:aws:sqs:ap-south-1:058264194338:video-queue

