services:
  app:
    image: shot-tube-app
    container_name: shot-tube-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env