services:
  server:
    image: server
    container_name: server_container
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - server/.env
  client:
    image: client
    container_name: client_container
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - client/.env
    depends_on:
      - server
