import { Router } from 'express';
import NotificationController from '../controllers/notification.js';
import { verifyJWT } from '../middlewares/auth.js';
const router = Router();
router.use(verifyJWT);
router.get('/all-notifications', NotificationController.getAllNotifications);
router.patch('/mark-as-read', NotificationController.markAsRead);
router.patch('/mark-all-as-read', NotificationController.markAllAsRead);
router.delete('/delete-notification', NotificationController.deleteNotification);
export default router;